server:
  port: 8082

spring:
  application:
    name: knowflow-knowledge
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:114.55.13.136:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:knowflow-knowledge-group}
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
  redis:
    host: 114.55.13.136
    port: 6379
    password: ${REDIS_PASSWORD:sqs@YH718369553}
    database: 0

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:114.55.13.136:8848}
    sentinel:
      eager: true
      log:
        dir: ${SENTINEL_LOG_DIR:${java.io.tmpdir}/knowflow-sentinel}
        switch-pid: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD_ADDR:127.0.0.1:8858}
        client-ip: ${SENTINEL_CLIENT_IP:127.0.0.1}
        port: ${SENTINEL_TRANSPORT_PORT:8721}

knowflow:
  kafka:
    topic: ${KAFKA_TOPIC:knowflow-knowledge-events}
